### ISSUE TITLE
Sub map pages haven't been updated with the new loading system

### ISSUE THREAD

**Issue by Norgaz** [LaeradAcies/Issues#18]
Not sure if this is a bug or not, but why hasn't this been done yet @minimitch0199?

**Comment by minimitch0199** [comment]
It is being worked on. Some problems have come up when trying to separate the genres from one another.   
Just sit back and wait. It'll come soon.

**Comment by Norgaz** [comment]
Ok. Also, the map stats aren't loading on the main maps page.

**Comment by minimitch0199** [comment]
That has now been fixed, @Norgaz.
